services:
  redis:
    image: redis:7-alpine
    container_name: web-crawler-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    container_name: web-crawler-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev_search_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111777uuS#
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
